name: Release on Master 😎

on:
  # This allows for manual triggering of the action
  workflow_dispatch:
  # This will run this action on every push to the master branch - update as required
  push:
    branches:
      - master

jobs:
  build-project:
    name: Build project ✨
    runs-on: ubuntu-latest

    # Enter in project properties here
    env:
      PROJECT_NAME: "SiberianGameJam2023"

    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - WebGL

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}

      # Build
      - uses: game-ci/unity-builder@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_NAME }}-${{ matrix.targetPlatform }}
          path: build/${{ env.PROJECT_NAME }}-${{ matrix.targetPlatform }}.zip

      #Upload to Pages (For WebGL builds)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: matrix.targetPlatform == 'WebGL'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/WebGL/${{ env.PROJECT_NAME }} # The folder the action should deploy. 

      # More details on usage here: https://github.com/marketplace/actions/create-release
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          prerelease: true
          allowUpdates: true
          tag: "0.0.1" # Or what ever tag you want, but there must be a tag!
          body: "Pre-release"
          artifacts: 'build/${{ env.PROJECT_NAME }}-${{ matrix.targetPlatform }}.zip'
          token: ${{ secrets.GITHUB_TOKEN }}

