name: Release on Master 😎

on:
  # This allows for manual triggering of the action
  workflow_dispatch:
  # This will run this action on every push to the master branch - update as required
  push:
    branches:
      - master

jobs:
  build-project:
    name: Build project ✨
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      #Upload to Pages (For WebGL builds)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Build/WebGL/ # The folder the action should deploy. 

